version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - ./instance:/usr/src/app/instance
    environment:
      - FLASK_ENV=development
      - OPENAI_API_KEY=sk-<your key here>
    depends_on:
      - db

volumes:
  db-data:
