version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - db-data:/usr/src/app/database  # Adjust the path as needed
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

volumes:
  db-data: